name: test-deployment

actions:
  step-one:
    image: node:latest
    steps:
      - echo "Hi"
      - echo "World"

  step-two:
    image: node:latest
    steps:
      - echo "Yo"
      - echo "What's up"
      
