version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get -qq update
      - run: sudo apt-get -qq install --yes python-dev 
      - run: sudo apt-get -qq install --yes python-pip
      - run: sudo pip install -U pip
      - run: sudo pip install awscli --upgrade
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run build
      - run: aws s3 rm --recursive s3://davidalsh.com
      - run: aws s3 cp --recursive ./dist s3://$BUCKET
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths /\*
