version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: npm build
      
  deploy:
    docker:
      - image: mesosphere/aws-cli
    working_directory: ~/repo
    steps:
      - run: aws s3 rm --recursive s3://davidalsh.com
      - run: aws s3 cp --recursive ./dist s3://$BUCKET
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths /\*

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
      - deploy